### ISSUE TITLE
 Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library [com.android.support:appcompat-v7:24.2.1] 

### ISSUE THREAD

**Issue by captain-miao** [Xiaofei-it/AndroidDataStorage#6]
Error:Execution failed for task ':android-data-storage:processDebugAndroidTestManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library [com.android.support:appcompat-v7:24.2.1] 
> ~/AndroidDataStorage/android-data-storage/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.2.1/AndroidManifest.xml
>     Suggestion: use tools:overrideLibrary="android.support.v7.appcompat" to force usage

**Comment by Xiaofei-it** [comment]
Which version of this project do you compile in your gradle file?

**Comment by captain-miao** [comment]
```
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
```

**Comment by Xiaofei-it** [comment]
No. What I mean is not the statements you gave me just now, but the following one:

```
compile 'xiaofei.library:android-data-storage:1.2.0'
```

Which version are you using? Have you tried the latest version, which is 1.2.0?

**Comment by captain-miao** [comment]
It's the AndroidDataStorage project, I upgraded the gradle version.😢

**Comment by Xiaofei-it** [comment]
Have you solved the problem you encountered?

**Comment by Xiaofei-it** [comment]
The minSdkVersion of v1.2.0 is 8, not 9. If you use v1.2.0, everything should have been OK.

Also, you can change the minSdkVersion of your own project into 9.

**Comment by captain-miao** [comment]
done

**Comment by Xiaofei-it** [comment]
OK.
